---
title: "Course content"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---

<html lang="en">

<br>

#

This course is taught in an active-learning format, which means that students are responsible for reading or watching all of the materials below **before** the corresponding class. In active learning courses, students are involved in
discussion, writing, problem-solving, and higher-order thinking during class time. The active learning activities that are planned for each class are shown below.

**Make sure to read, watch, or listen to all content on each tab before the corresponding class!**

If you are a FISH 521 student, this website will be your resource for all course content, but we will use Canvas for announcements, submitting assignments, and keeping track of grades.

<br>

**Navigating a slide deck**

* Use the arrow keys (&#8592;/&#8594;) on your keyboard to go forward or backward
* Press the "o" key on any slide to show you an overview of the slide deck
* In overview mode, click on a slide or press "esc" to zoom in on it
* You can also print the slides to a pdf by selecting the "print" option from your browser's File menu.

<br>


# Classes

<br>

## Class 1: Skills to get up and running

**Topics to be covered:**

* Course overview
* Building a mentorship network
* Time management
* Writing habits
* Searching the literature
* Reference management
* What do you want to learn this quarter?

**Required readings:** 

* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Introduction
* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 2: Building your team
* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 3: Deciphering academic jargon
* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 4: Reading and writing about other people's research
* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 5: Staying on track in your program
* [Google Scholar search tips](https://scholar.google.com/intl/en/scholar/help.html)
* [Mentoring practices that promote graduate student success](https://doi.org/10.1371/journal.pone.0305367)
* Use your uw.edu identity to register on the [National Center for Faculty Development and Diversity website](https://members.ncfdd.org/dashboard) (UW has an institutional membership, so you can register for free)

**Required videos:** 

* [NCFDD Skill #1: Every semester needs a plan](https://members.ncfdd.org/webinars/semesterplan25fall)
* [NCFDD Skill #2: How to align your time with your priorities](https://members.ncfdd.org/webinars/25weeklymeet)
* [NCFDD Skill #3: How to develop a daily writing practice](https://members.ncfdd.org/webinars/dailywriting25)
* [NCFDD Skill #4: Mastering academic time management](https://members.ncfdd.org/webinars/masteringtime25)
* [NCFDD Skill #7: Cultivating your network of mentors, sponsors, and collaborators](https://members.ncfdd.org/webinars/cultivatingyournetwork25)

**In-class activities:** 

* [In-class presentation](lectures/week_01/lec_01_class_overview.html)
* Developing a time management system that works for you
* Creating your mentoring map
* Developing your literature search strategies
* Subscribing to journal table of contents alerts
* Choosing and setting up a reference management system
* Brainstorm: what else do you want to learn this quarter?

<br>

## Class 2: How to do science

**Topics to be covered:**

* How to ask scientific questions
* Structuring a proposal
* Using a message box

**Required readings:** 

* [Research and experimental design](https://wood-lab.github.io/fish_521/references/Garton_et_al_2020.pdf)
* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 6: Doing research and finding funding
* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 7: Writing about your research
* [Proposal recipe](https://wood-lab.github.io/fish_521/references/proposal_recipe.jpg)
* [Message box](https://wood-lab.github.io/fish_521/references/message_box.pdf)

**Required videos:** 

* [NCFDD Skill #5: Moving from resistance to writing](https://members.ncfdd.org/webinars/resistancetowriting25)
* [COMPASS: Crafing a communication plan](https://www.youtube.com/watch?v=Bn-axDQQhds)

**In-class activity:** 

* [In-class presentation](lectures/week_02/lec_02_proposals_abstracts.html)
* The scientific method
* Trade-offs between certainty and scope of inference in experimental design
* Proposals
* Craft your message using a message box

<br>


## Class 3: Writing a manuscript

**Topics to be covered:**

* Manuscript structure
* Writing an abstract
* Manuscript life cycles (including response to reviewers)
* Authorship and contributions

**Required readings:** 

* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 8: Publishing and promoting your work
* Kevin Lafferty's [How to write a scientific paper](https://wood-lab.github.io/fish_521/references/Lafferty_how_to_paper.pdf)
* [How to write a *Nature* abstract](https://wood-lab.github.io/fish_521/references/nature_summary_paragraph.pdf)
* [Guidelines for authorship in the field of ecology](https://wood-lab.github.io/fish_521/references/Weltzin_ecology_authorship.pdf)
* [Avoiding and overcoming authorship conflicts](https://wood-lab.github.io/fish_521/references/Cooke_10_rules_authorship.pdf)

**Required videos:** 

* [How to write a scientific paper from start to finish](https://www.youtube.com/watch?v=udJ3AnS2veU)
* [Structure of a manuscript](https://www.youtube.com/watch?v=lTnltrzzTzw)
* [How to get started on a manuscript](https://youtu.be/xcIfCrOe45k?si=tv-fOe4xe4YR8UDl)
* [Manuscript life cycle](https://youtu.be/r51GU4c-b9s?si=oFNqcJL0aKY4WjE8)
* [Authorship on manuscripts](https://youtu.be/_xbNe54Y-hY?si=He-ZHlhFWrOb3jr3)
* [Authorship order on manuscripts](https://youtu.be/WuvwdR-WyNw?si=aYZ2VAeFbLFSP0lh)

**In-class activity:** 

* [In-class presentation](lectures/week_04/lec_03_manuscripts.html)

<br>


## Class 4: Publishing a manuscript

**Topics to be covered:**

* Choosing a journal and author guidelines
* Writing a cover letter
* Supplementary material
* Reproducibility

**Required readings:** 

* [How to write a cover letter](https://wood-lab.github.io/fish_521/references/cover_letter_template.pdf)
* [How to recognize a predatory journal](https://wood-lab.github.io/fish_521/references/Oviedo-Garcia_2021.pdf)
* [Bookmark this list of predatory journals](https://beallslist.net)
* [Good enough practices in scientific computing](https://wood-lab.github.io/fish_521/references/Wilson_et_al._2017.pdf)
* [BES guide to reproducible code](https://wood-lab.github.io/fish_521/references/BES_guide_to_reproducible_code.pdf)
* [Packaging data analytical work reproducibly using R](https://wood-lab.github.io/fish_521/references/Marwick_etal_2018_research_compendia.pdf)

**Required videos:** 

* [Choosing a journal for your manuscript](https://youtu.be/VUobJuDxJio?si=nO-pUKNmSeaUNPV7)
* [Writing the cover letter for your manuscript](https://youtu.be/52OyqlGrUhE?si=3y3VqAbfazAbvoxv)
* [What goes into supplementary material?](https://youtu.be/ytmWAfobmAc?si=YN4nXxdI-odOJIcQ)
* [Reproducibility](https://youtu.be/N0fu3hbhN8k?si=geTzW_k9VoE7tnUF)
* [How to deal with manuscript rejections](https://www.youtube.com/watch?v=ZpZNTEHVmdw)
* [Revising a paper after peer review](https://youtu.be/j-px82MMmA4?si=5yWZMWdVYk-xBlOD)
* [How to revise and resubmit in no time](https://members.ncfdd.org/hhchapter6)

**In-class activity:** 

* [In-class presentation](lectures/week_05/lec_04_manuscripts_2.html)

<br>


## Class 5: Reviewing a manuscript

**Topics to be covered:**

* Reviewing a manuscript or proposal

**Required readings:** 

* [BES guide to peer review](https://wood-lab.github.io/fish_521/references/BES_guide_to_peer_review.pdf)
* [Taylor & Francis guide to peer review](https://wood-lab.github.io/fish_521/references/taylor_francis_reviewer_guide.pdf)
* [Tips and tricks for writing constructive peer reviews](https://wood-lab.github.io/fish_521/references/Clements_et_al_2025.pdf)
* [Unprofessional peer reviews](https://wood-lab.github.io/fish_521/references/Silbiger_2019_peer_review_urm.pdf)
* [Overly harsh peer reviews](https://wood-lab.github.io/fish_521/references/Clements_2020_prig_peer_review.pdf)
* [Quantifying professionalism in peer reviews](https://wood-lab.github.io/fish_521/references/Gerwing_2020_prof_peer_review.pdf)

**Required videos:** 

* [How to critically evaluate a research paper](https://www.youtube.com/watch?v=64DHO3hAeSM)
* [How to provide a constructive peer review of a paper](https://youtu.be/cL7ktwQBg4I?si=GnUTAiQlccgsntgc)

**Required preparation:**

You have been assigned to review two real-life proposals submitted to funding agencies by Chelsea: either Proposals 1a and 1b or Proposals 2a and 2b. Here are the proposals:

* Coral reef parasites: [Proposal 1a](https://wood-lab.github.io/fish_521/references/proposal_1a.pdf)
* Coral reef parasites: [Proposal 1b](https://wood-lab.github.io/fish_521/references/proposal_1b.pdf)
* Gulf of Alaska parasites: [Proposal 2a](https://wood-lab.github.io/fish_521/references/proposal_2a.pdf)
* Gulf of Alaska parasites: [Proposal 2b](https://wood-lab.github.io/fish_521/references/proposal_2b.pdf)

Within each pair of proposals, one was funded and one was not. Your job is to provide a review of each proposal, using the [NSF template](https://wood-lab.github.io/fish_521/references/nsf_review_template.docx) (see [NSF review criteria](https://www.nsf.gov/policies/pappg/24-1/ch-3-proposal-processing-review#a-merit-review-principles-and-criteria-af2) for details of what to look for). You do not need to submit your review, but you should complete it because it will prepare you to engage in the mock panel we will hold in class. For each pair of proposals, the panel will decide which to fund. I'll tell you at the end of class whether you chose the same proposal that the funder chose.

**In-class activity:** 

* [In-class presentation](lectures/week_06/lec_05_reviewing.html)
* Mock NSF review panel

<br>


## Class 6: Communication

**Topics to be covered:**

* How to give a scientific presentation

**Required readings:** 

* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 9: Talking about your research
* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 10: Going to conferences
* Kevin Lafferty's [How to give a scientific presentation](https://wood-lab.github.io/fish_521/references/Lafferty_essay.pdf) - Kevin is one of the best speakers I know and this essay is jam-packed with useful advice!

**Required videos:** 

* [Giving an effective scientific presentation](https://www.youtube.com/watch?v=Hp7Id3Yb9XQ)
* [Here's what you're going to be asked to do in class](https://vimeo.com/336397662)

**In-class activity:** 

* [In-class presentation](lectures/week_07/lec_06_scicomm.html)
* [Grad Slam exercise](https://gradslam.universityofcalifornia.edu)

<br>
  

## Class 7: Practice proposal presentations + websites

**Topics to be covered:**

* Your practice proposal presentations! Sign-up with your uw.edu identity [here](https://docs.google.com/spreadsheets/d/10H6DrWte3cjqrg5sqQu5wIiKtXmylq7JR4ZqWBClcRY/edit?usp=sharing).
* Web presence

**Required readings:** 

* [Install Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
* [Creating a free website via Markdown](https://wood-lab.github.io/fish_521/lectures/week_07/lec_06b_websites.html)
* [Online outreach](https://wood-lab.github.io/fish_521/references/Bik_2015_ten_simple_rules.pdf)
* If you already have a professional website, please come to class prepared to work on it (make sure you have your password and whatever else you need to access it). If you don't yet have a website, we'll work through the process of using GitHub to launch a free website for you.

**Required videos:** 

* [Personal websites for scientists](https://www.youtube.com/watch?v=3g-bNajtxZE)

**In-class activity:** 

* Your practice proposal presentations! Sign-up with your uw.edu identity [here](https://docs.google.com/spreadsheets/d/10H6DrWte3cjqrg5sqQu5wIiKtXmylq7JR4ZqWBClcRY/edit?usp=sharing).
* [Let's make a website!](lectures/week_07/lec_06b_websites.html)

<br>


## Class 8: How to do it all

**Topics to be covered:**

* Your final proposal presentations! Sign-up with your uw.edu identity [here](https://docs.google.com/spreadsheets/d/1PIv0UwwatBUK20fSi7EkkughOe4lqaWcNTrsSXGqJoo/edit?usp=sharing).
* How to secure letters of recommendation and ensure that they are spectacular
* (by popular request) E-mail etiquette
* (by popular request) Special considerations for ADHD/AuDHD/autistic scientists
* (by popular request) How to organize your stuff and find it again later
* How to get what you want
* How to do it all without overdoing it

**Required readings:** 

* [*Field Guide to Graduate School*](https://press.princeton.edu/books/paperback/9780691201092/a-field-guide-to-grad-school?srsltid=AfmBOooNXYYd-0yyIIr7Mz0qAQNxbQ8wfWQz-Qod86wn9DO9pQPIWTcE) Chapter 12: Balancing teaching, research, service, and life

**Required videos:** 

* [NCFDD Skill #6: The art of saying no](https://members.ncfdd.org/webinars/artofno25)
* [NCFDD Skill #8: Overcoming academic perfectionism](https://members.ncfdd.org/webinars/academicperf25)
* [NCFDD Skill #10: How to manage stress, rejection, and haters in your midst](https://members.ncfdd.org/webinars/rejection25)
* [NCFDD Hidden Handbook: The art of saying "yes": Seeking and securing opportunities in academia](https://members.ncfdd.org/hhchapter9)

**In-class activity:** 

* Your final proposal presentations! Sign-up with your uw.edu identity [here](https://docs.google.com/spreadsheets/d/1PIv0UwwatBUK20fSi7EkkughOe4lqaWcNTrsSXGqJoo/edit?usp=sharing).
* [In-class presentation](lectures/week_10/lec_08_panel.html)

<br>


<center>*This site was last updated at `r format(Sys.time(), "%H:%M")` on `r format(Sys.Date(), "%d %b %Y")`*</center>