---
title: "Course overview"
subtitle: "Proposal writing & professional development<br>FISH 521"
author: "Chelsea Wood"
date: "5 January 2026"
output:
  ioslides_presentation:
    css: lecture_slides.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## {.flexbox .vcenter .bigger}

<font size="10">
WHO AM I? 
</font>


## Chelsea Wood

* Assistant Professor, SAFS (2016-2021)

> - Associate Professor, SAFS (2021-present)

> - Graduate Program Coordinator, SAFS (2023-present)

> - Associate Director, SAFS (2023-present)

> - Grew up on Long Island, NY

> - BS from Dartmouth (advisor: Kathy Cottingham)

> - PhD from Stanford (advisor: Fio Micheli)


## {.flexbox .vcenter .bigger}

<font size="10">
MY QUALIFICATIONS? 
</font>


## Chelsea Wood

* Author of 70+ peer-reviewed papers, one published book, and one in-prep book

> - Assistant Editor, *Frontiers in Ecology and the Environment* (2006-2008)

> - Subject Matter Editor, *Ecology* (2021-present)

> - Associate Editor, *Proceedings B* (2018-present)

> - Associate Editor, *Journal of Animal Ecology* (2021-present)

> - Peer reviewer for 40+ journals

> - Proposal reviewer for US National Science Foundation and the national science foundations of 7 other countries


## My role as course instructor

> - Help you learn the material

> - Be a resource for you into the future


## {.flexbox .vcenter .bigger}

<font size="10">
WHO ARE YOU? 
</font>


## Introduce yourself with the following:

1. Your name & pronouns

2. Your advisor/lab

3. Your home town

4. Your undergraduate school

5. Your research area(s) of interest

6. What you'd like to get out of this course


## {.flexbox .vcenter .bigger}

<font size="10">
Course logistics 
</font>


## {.flexbox .vcenter .bigger}

<font size="10">
[__Course information__](https://wood-lab.github.io/fish_521/)
</font>


## What to expect

1. 4 credits = 12 hours / week

2. Expect to spend substantial time reading/watching/writing outside of class

3. Expect to spend in-class time engaged in discussion, writing, problem-solving, and higher-order thinking

4. Expect to struggle, and to emerge from the class with better skills for taking advantage of professional opportunities - including a draft of your thesis/dissertation proposal


## {.flexbox .vcenter .bigger}

<font size="10">
Course goal
</font>


## Course goal

To teach you all the professional skills that grads are usually expected to pick up on their own, including:

* self-management
* networking
* developing a project
* writing and submitting manuscripts
* reviewing manuscripts and proposals
* marketing yourself
* presentation skills
* collaboration skills
* what else do you want to learn?


## {.flexbox .vcenter .bigger}

<font size="10">
Building a mentorship network
</font>


## There is no guru

One person cannot give you everything you need to grow as a scientist. Relying on a mentorship network is more sustainable, and gives you access to a broader range of expertise and experience.


## &nbsp; {data-background=mentoring_network.png data-background-size=60%}


## {.flexbox .vcenter .bigger}

<font size="10">
Time management
</font>


## A unique time management system that works for you

You need a system to organize all of the tasks that are falling on your desk. Your system needs to work for your brain, but it should have three elements:

* A list of things to do
* A way to connect those things to specific times when they will be done
* A standing time to organize


## Here's what works for me

* A list of things to do: ToDoist
* A way to connect those things to specific times when they will be done: Google Calendar
* A standing time to organize: Chelsea's weekly meeting

* What works for you? Let's try some stuff.


## {.flexbox .vcenter .bigger}

<font size="10">
Becoming a good writer
</font>


## Resources

[National Center for Faculty Diversity and Development - use your uw.edu to create an identity and access NCFDD learning materials](https://www.ncfdd.org)

[Karban R, Huntzinger M, and Pearse IS. 2023 *How to Do Ecology*. Princeton University Press.](https://press.princeton.edu/books/paperback/9780691245751/how-to-do-ecology?srsltid=AfmBOooPTZ96ssF7Ud_KkCNYCkD3L7vehR9N45eHxNL7-T7WHIDtHutB)

[Zinsser W. 2016. *On Writing Well*. Harper Perennial.](https://www.harpercollins.com/products/on-writing-well-william-zinsser?variant=32118081159202)

[Heard SB. 2016. *The Scientist’s Guide to Writing*. Princeton University Press.](https://press.princeton.edu/books/hardcover/9780691219202/the-scientists-guide-to-writing-2nd-edition?srsltid=AfmBOop0xOEJao68_qK8KedwGOZKvcOX1Wh8-7I_PabbuZjkzKfFOj5e)


## Communication is central to science

> - Data are great, but if insights from data are not shared, they do not advance our understanding of nature (which is the point of science).

> - Insights from data are shaped and shared via communication - papers, yes, but also proposals, talks, peer reviews, websites, socials.

> - This course is designed to sharpen your communication skills, especially your writing skills.


## Writing is hard...

Very few writers are geniuses - most find it difficult and time-consuming. Even some "geniuses" struggle. Here's what Steven King has to say about it:

"Stories are relics, part of an undiscovered, pre-existing world. The writer’s job is to use the tools in his or her toolbox to get as much of each one out of the ground intact as possible."

When you're writing, imagine yourself on an archaeological dig. Just because progress is incremental and back-breaking doesn't mean you are doing it wrong.


## ...but the rewards for writing well are great.

* Influential papers that change the world's understanding of nature

> - Memorable talks that change your colleagues' minds

> - Successful proposals that allow you to do the science you want to do

> - Students whose trajectories you will bend

> - Regular folks whose understanding of nature is enriched by their interaction with you

> - Connection in an isolating age


## So what's the secret for effective communication?

* Writing (especially scientific writing) is a craft, not an art

> - Anyone can get better at writing with practice and deliberate attention

> - Half the battle is self-management - developing good writing behavior


## Reading & writing go hand-in-hand

* When reading, make notes about things you (dis)like

> - If you like a paper, why do you feel that way?

> - What wording, structure, and graphics do you find most effective?

> - If you don't like a paper, or it's hard to understand, what elements are you struggling with?


## Writing behavior

Writing typically goes slowly for 3 reasons:

1. Lots of time spent writing, editing, rephrasing, reorganizing

2. Distractions

4. You're spinning your wheels because you haven't set the stage for success


## Sound familiar?

Heard (2016, p22) writes

"For instance, after opening the blank document that was to become [Chapter 4], but before writing anything past the title, I checked my email four times, read news articles in the New York Times and the Toronto Globe and Mail, went to the greenhouse to weed (unnecessarily) goldenrods growing for an experiment, read the latest postings on a baseball blog, a computer-security blog, and two economics blogs, and thought hard about whether is was close enough to noon to heat up my lunch. (Sadly it wasn't.)"


## Encouraging self-awareness

**Reminders**

> - Put a sticky note on your monitor that asks, "*How* are you writing?"

> - Are you actually writing or doing something else?


## Encouraging self-awareness

**Writing log**

> - Choose a 2+ hour block for writing

> - Set an alarm for every 6-10 minutes and note what you've been doing


## Encouraging self-awareness

**Cooperation**

> - Discuss behaviors with a friend or colleague

> - Send copies of daily accomplishments or exchange writing logs


## Encouraging self-awareness

**Quieting your inner critic**

> - Do you hear a little voice criticizing you or your work? That's your inner critic.

> - He's trying to protect you. He doesn't realize that he's not helping.

> - If he's being particularly loud, you can write down what he says to you. Getting it out in the open can help reveal it as false or you can discuss with a friend.

> - Gently thank your critic for trying to protect you; tell him you're safe and he isn't needed.


## Encouraging self-awareness

**Setting the stage for success**

> - Block out writing time on your calendar, just as you would for a meeting, and honor it the way you would honor a meeting.

> - At least 30 minutes for writing, every work day. No more than 3-4 hours of writing per day.

> - Writing every day minimizes your start-up time. You'd be surprised how much you can get done in small, consistent increments.

> - When does your brain work best? Schedule your writing time for that part of the day.


## Behavioral challenges

**Avoidance**

> - Procrastinators ("I need a snack")

> - Intentional non-starters ("I'll save this for tomorrow")


## Behavioral challenges

**Distraction**

> - Consider your environment and time of day

> - What else is going on in your life?


## Behavioral challenges

**Feeling stuck ("writer's block")** 

> - Lower your standards

> - Divide and conquer

> - Change your environment or take a break

> - Talk it out

> - Freewrite


## Behavioral challenges

**Perfectionism**

> - Try to get *something* on paper & edit it later

> - This strategy is sometimes called "barf and buff" or "write drunk, edit sober."


## Behavioral challenges

**Fear of criticism**

> - Red ink can be triggering

> - Accept constructive criticism and make it work for you


## {.flexbox .vcenter .bigger}

<font size="10">
Searching the literature
</font>


## Finding papers of interest?

* Word of mouth

* Journal table of contents

* Online searches


## Web of Science (WOS)

* WOS is a powerful and popular option

* Find it online [here](https://guides.lib.uw.edu/az.php)


## Google Scholar

* Google Scholar is another option

* Find it online [here](https://scholar.google.com/schhp?hl=en)

* **Note**: results will vary between WOS & Google


## {.flexbox .vcenter .bigger}

<font size="10">
Reference management
</font>


## Staying organized

### Reference management software has 2 benefits:

1. keeps your references organized and easily searchable

2. (generally) integrated with word processing software to create citations and literature cited section


## Software options

| Software | Pros | Cons |
|:--:|:---|:---|
| [EndNote](https://endnote.com/downloads) | works with MS Word | not free |
| [Zotero](https://www.zotero.org/download/) | works with MS Word; browser plug-in | can be hard to share |
| [Mendeley](https://www.mendeley.com/download-reference-manager/) | works with MS Word | can be hard to share | 
| [Paperpile](https://paperpile.com) | works with Google Docs | costs $2.99/month |
| [BibTeX](http://www.bibtex.org/) | works with LaTeX & Markdown | antiquated |


## Subscribing to journal ToC alerts

* this is a great way of staying on top of the literature!
* let's do it together
