---
title: "Peer reviews"
subtitle: "Proposal writing & professional development<br>FISH 521"
author: "Chelsea Wood"
date: "9 February 2026"
output:
  ioslides_presentation:
    css: lecture_slides.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Peer review process


## What is peer review?

* A collaborative process that allows independent experts to evaluate and comment on manuscript submissions

> - Peer review gives authors feedback to improve their work & allows the editor to assess the paper's suitability for publication


## Kinds of peer review

* **Single-blind**: reviewer's name is not disclosed to the author(s)

> - **Double-blind**: neither identity of the reviewers and authors are disclosed

> - **Open**: both the author and reviewer names are disclosed

> - **Post-publication open**: editor mediates readers' and reviewers' comments after publication


## Why do peer review?

* Improves the quality of articles that are published

> - Provides an assessment of the science in the literature

> - Assists the editorial decision-making process

> - Screens for unethical practice


## Why do peer review?

* Keep abreast of latest research

> - Improve your own writing

> - Boost your career


## Who does peer review?

Generally people with

* many years of research experience in a subject area

> - in-depth study in a specific area during grad school

> - practical experience in the field

> - recently published articles on a related subject


## How do I become a reviewer?

* Contact the editor

> - Ask a senior colleague to recommend you

> - Look out for calls for reviewers

> - Find a mentor

> - Be visible on researcher networking sites (e.g., your own website, [ResearchGate](https://www.researchgate.net/), Google Scholar)

> - Write a paper!


## How does the process work? {data-background=peer_review_process.png data-background-size=98% data-background-position="50% 100%"}


## Best practices | Reviewer invitation

Things to consider:

* Does the subject area of the article match my expertise?

> - Do I have time to do the review within the time frame requested (2-3 weeks)?

> - Do I have any conflicts of interest?

> - Do I actually want to review this article?

> - Can I commit the necessary time (it's OK to ask for an extension)?


## Best practices | Reviewer invitation

* If declining an invitation, do so promptly

* If possible, suggest alternate reviewers


## In-class exercise {.smaller}

What would your response be to an email like this & why?

Dear Dr. Wood: 

Pleased to be inviting you to review a manuscript titled "Changes in the age at maturation for two species of Cyprinid minnow raised in an aquaculture setting", which has been submitted to *The Journal of Fisheries Research*. Given your extensive background in this field, your advice would be best appreciated.  

Click [here]() to accept.

Click [here]() to decline.

Sincerely,  
Maya Livingstone  
Editor, MDPI Journals


# Writing constructive reviews


## Best practices | Basic principles

* Always treat the paper with the utmost confidentiality

> - Always be professional, courteous & collegial

> - Take an objective, independent approach to the work

> - Be attentive & critical

> - Provide evidence for any statements you make

> - Use simple language

> - Never contact the authors directly


## In-class exercise | {data-background=NSF_logo.png data-background-size=66% data-background-position="50% 80%"}


# Ethics in peer review


## Confidentiality

* You must not take ideas presented in articles you review & pass them as your own

> - You must not disclose any data presented in the article

> - However, you can ask a colleague for advice as long as necessary details remain confidential (e.g., author names)


## Bias

We all have unconscious biases that affect our ability to conduct reviews

* **gender bias**: articles by authors of either sex are subjected to different standards of review

> - **geographical bias**: authors' country of origin will influence the manner in which their work is assessed

> - **seniority bias**: articles by authors at different stages in their careers will be subject to more or less favorable review

> - **confirmation bias**: articles reporting controversial or new ideas will be less favorably reviewed than articles that do not challenge conventional wisdom


## Duplicate submission & publication

* **Do not** submit a paper to various journals concurrently

> - **Do not** submit a paper with overlapping material, especially results, to different journals


## Authorship

* Recall that authorship is usually granted to those who have substantially contributed to the work presented in an article

> - **Unjustified authorship**: honorary or guest authorship assigned to people who have not made substantial contribution to the conception, design, acquisition of data, or analysis and interpretation

> - **Ghost authorship**: people who have contributed to authorship of the paper are omitted from the list of authors


## Data

Unfortunately, not all data are what they appear

* Fabricated data are made up rather than the result of actual measurements

> - Falsified data arise from measurements that have been unjustifiably altered in order to yield more impressive/convenient results

> - Theft of data someone else's data without their consent

> - Animal welfare practices need to be followed when carrying out research


## Conflict of interest

* **Reviewers**: Colleagues or friends of authors who cannot provide an impartial review

> - **Authors**: Funding or association with an organization may raise questions about motivation and findings

